### ISSUE TITLE
Incompatibilities:  [1.12] RPG-HUD-3.6.3

### ISSUE THREAD

**Issue by XvSkItZvX** [KurodaAkira/RPG-Hud#17]
Let me begin by saying I was extremely excited when I seen that work had began on this mod again, and that you had ported it up to 1.12, thank you very much.

I have began looking into 1.12 to build a mod pack, beginning with a number of mods that affect the Client Interface and/or Performance.

I will gladly work with you and supply you with any information needed not only to resolve the issues I have encountered on my first couple of tests, but to also test additional features.

First: I observed what appears to be an incompatibility between RPG-HUD and another mod, [TabbyChat 2](https://minecraft.curseforge.com/projects/tabbychat-2), that modifies the chat interface. 
- Effect is that regardless of rendering settings within RPG-HUD "chat" option I am unable to see the chat what so ever. Be it the log, or the input line none of it is visible with both mods enabled. TabbyChat is a stylish chat interface with a number of features that if they could both work together I feel would compliment, as well as be enhanced by,  the RPG-HUD. 

Second: This isn't quite an incompatibility, though possibly a feature or something perhaps you and the other developer can collaborate on. One of the other mods on my list of highly useful mods is [Quick Hotbar](https://minecraft.curseforge.com/projects/quick-hotbar). A mod that allows access to inventory through a number of key combinations and mouse wheel scrolling. Both mods work as expected together. The issue is that they don't quite line up except under the "Extended", "Textured" and "Vanilla" hud types, which really limits some of the more beautiful styles of RPG HUD. (I'm honestly partial to the Modern HUD)

Third: Also not an incompatibility, and likely something the other developer will be able to facilitate a solution for. [AppleSkin](https://minecraft.curseforge.com/projects/appleskin), a mod that simply provides an overlay of the saturation mechanic on the hunger bar. By default it highlights the drumsticks with a yellow outline. I have already messaged the developer of the mod and requested the ability to move the overlay and with a bit more work on the users side it may be possible to use resource packs to tweak the appearance to fit with the aesthetics of the RPG HUD. Though I also feel that, with the mod being licensed under the "Public Domain", there would be potential for you to incorporate that functionality into the HUD much more seamlessly. 

Finally: While I am doing the testing, I find myself jumping in and out of creative or even spectator modes. The Interface changes are really disorienting for whatever reason I feel completely lost. I'm not fond of how vanilla does it other honestly but it's not as drastic of an interface change in vanilla. I suspect that because of the way vanilla is coded this may not even be possible. But could you provide an option to keep the HUD when in creative with only subtle changes to indicate the current mode?

Thank you once again and in advance, and if there is anything I am capable of doing to help feel free to let me know.

**Comment by Raelzaryn** [comment]
1. The issue with tabby chat is known and should be fixed (refer to https://github.com/KurodaAkira/RPG-Hud/issues/4#issuecomment-287504291) there should be an option in the settings to "force vannila chat". That one should let tabby chat access it properly.

2. That one is an issue I can't do much about since I have to change the display height of the hotbar.
To fix this please talk to the creator of quick hotbar to add compatiblity for hotbars in different locations (adding a possible offset would work there)

3. I tried doing that before. Unfortunatly I couldn't figure it out using vanilla mechanics so I'll have to add compatiblity which I have no diea how to do (and currently no time to figure out). - So for now this one is on hold.

4. You want an option to make the HUD persist even if you are in creative mode? Definitly doable. WIll add that.

**Comment by XvSkItZvX** [comment]
Awesome, thanks for the response, Not sure how I missed the prior comment sorry about the duplication. 

I will address TabbyChat at the end of this post (out current order) because It will comprise the majority of the topic in this reply. 

Quick Hotbar: I will glad contact the developer of that mod, not sure why I hadn't considered it at the same time I decided to contact the dev, Squeek, about appleskin. 

And speaking of the AppleSkin mod, I received a response from the fore mentioned Sqeek. Unfortunately the response was quite technical and left me with the impression he had no intentions of doing so, but here's a good tip on how I could. Sadly I cannot, but I am going to pass the information along for if/when you manage the time to revisit the issue. 

Quote taken from his response on his [Git](https://github.com/squeek502/AppleSkin/issues/13#issuecomment-318570896).
> It should be possible for you to move the hunger bar and AppleSkin's overlays (along with any other mods that modify hunger bar rendering) by using GL functions to translate the position before and after rendering.
> 
> An example of this can be found here:
> https://github.com/RebelKeithy/DualHotbar/blob/master/src/main/java/com/rebelkeithy/dualhotbar/RenderHandler.java#L230-L269

About the Request for persistence. Awesome! Thank You!...Probably isn't even a feature most people would care about, and likely something I'm in the minority of having. Honestly it doesn't even have to really function, but I find myself hugely disoriented when switching between the two game modes. I greatly appreciate your efforts, and with an understanding of all the work Mod Devs do just so other people without the skills to do "cool stuffs" in the game there is no rush or pressure to do so. 

And finally, back to TabbyChat...
 Of the four Options under the Chat Settings,  I have tried a number of combinations, obviously not all possible, but quite a few. 

Force Rendering: Off - I leave it at this setting as my understanding of the function is related to RPG-HUD's modifications.

Prevent Event: Off - I have changed this a couple of times with the various changes I've made to the following two options.

Render Vanilla Element: On - This is the setting that makes most sense to me and I have set to both Off and On hoping it made a difference with the "Prevent Event" option. 

Prevent Rendering: On - This is the setting that makes the most sense to me as I believe this also affects RPG-HUDs modifications.

During the various combinations I have attempted, even restarting the client between alterations, I am still unable to make it appear. I doubt, but don't discount, the possibilities of this being an interaction of a combination of mods. 

If there is a specific setting, and or method of invoking the updated settings, I may have missed in my attempts point them out and I'll gladly try them again. Otherwise I don't seem to be able to get it to work.

If you are interested in the list of mods I am currently using in this environment, I will gladly make the list public on my ModLister page. It may provide insight into whether or not this isn't an interaction between other mods in combination between RPG-HUD and TabbyChat. 

Again, thank you very much for your efforts and contributions. I am willing to help in any way I'm capable.

**Comment by XvSkItZvX** [comment]
After posting I went back to play with the settings again. Switching the "Prevent Rendering: Off" option...
While it is not the TabbyChat interface, even after restarting the client, I does bring up the chat log. The input field however is still not visible. 

------------------------------------------------------------------------------------------------------------------
Original Content after accidentally closing the thread and using this to reopen.
> Oops...Seems I misunderstood the "Comment and Close" button...wouldn't have though I had the ability to do so lol.

Edited as to prevent this from becomming cluttered.

**Comment by XvSkItZvX** [comment]
When I replied earlier I wasn't in a position to mess with trying to get it to work more than just a couple of minutes. I just had more time and decided to just randomly change the options that I hadn't messed with before. 

It may be of benefit to other users of these two mods if you included these settings "Somewhere" lol.

Force Rendering: On
Render Vanilla Element: On
Prevent Event: Off
Prevent Rendering: Off

With these settings, not only is all aspects of chat visible, the TabbyChat interface is working fine as well. I will leave it to your discretion to close the thread. However outside of the other features, the primary issue is resolved.

**Comment by Raelzaryn** [comment]
Glad to hear it works for you now. Sorry I couldn't help you more but I don't play Minecraft for a while now.
I'll close this but open a separate one for the appleskin features.
